### ISSUE TITLE
Toy_sentiment_API

### ISSUE THREAD

**Issue by ghost** [melvynator/ELK_twitter#11]
Hi, I have installed the toy api sentiment because I would like to use it with another app I have for twitter but I don´t know how it works. I run it and appear this:

![imagen](https://user-images.githubusercontent.com/45429997/49929955-efcbf880-fec3-11e8-8f4e-48a9bbc4e38b.png)

I got into the localhost, and it didn't works.

Thanks

**Comment by melvynator** [comment]
@alannaparker45 Hey thanks for your interest. Those logs are just saying that the application is running on localhost on the port 5000.  The Logstash pipeline is going to use it to send the tweet content as a POST request, you can see it here in the configuration file: https://github.com/melvynator/ELK_twitter/blob/19d20a30e25e650b7fbb85bb7f9a08aa7a6fbdb2/src/twitter-pipeline/config/twitter-pipeline.conf#L121
