### ISSUE TITLE
Migrate to 6.X

### ISSUE THREAD

**Issue by melvynator** [melvynator/ELK_twitter#7]

**Comment by monsirto** [comment]
Looking forward to the v6 update. Obviously there are issues with the single document_type

**Comment by melvynator** [comment]
@monsirto 

Update done. The cause of having multiple data type in my index was due to a "RDBMS" thinking. In RDBMS you have to normalise your data. In Elasticsearch normalising your data is a bad practice. So I denormalise the data. Instead of having:

```
{
     "tweet": "Hey whats'p in Elastic?",
     "date": "TUE 19 DEC 16:08:21",
     "user_id": "1234567890"
}
```

```
{
     "name": "Melvyn",
     "user_id": "1234567890",
     "user_location": "France, paris"
}
```

I have the following:

```
{
     "tweet": "Hey whats'p in Elastic?",
     "date": "TUE 19 DEC 16:08:21",
     "user": {
             "name": "Melvyn",
             "user_id": "1234567890",
             "user_location": "France, paris"
      }
}
```

This is called data denormalisation.
